# Generated by Django 4.2 on 2023-09-18 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("storage_units", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("service_providers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storageunitprovider",
            name="location",
            field=models.ManyToManyField(
                blank=True,
                related_name="storage_location",
                through="storage_units.StorageFacility",
                to="service_providers.location",
            ),
        ),
        migrations.AddField(
            model_name="storageunitprovider",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organizers",
            name="location",
            field=models.ManyToManyField(
                blank=True,
                related_name="organizers_location",
                to="service_providers.location",
            ),
        ),
        migrations.AddField(
            model_name="organizers",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="movers",
            name="location",
            field=models.ManyToManyField(
                blank=True,
                related_name="movers_location",
                to="service_providers.location",
            ),
        ),
        migrations.AddField(
            model_name="movers",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
