# Generated by Django 4.2 on 2023-09-18 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MoverOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("commercial", "Commercial"),
                            ("public", "Public"),
                            ("business", "Business"),
                            ("personal", "Personal"),
                        ],
                        default="personal",
                        max_length=255,
                    ),
                ),
                ("pending", models.BooleanField(default=False)),
                ("proccess", models.BooleanField(default=False)),
                ("completed", models.BooleanField(default=False)),
                ("from_date", models.DateField(blank=True, null=True)),
                ("to_date", models.DateField(blank=True, null=True)),
                ("size", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OraganizerOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("commercial", "Commercial"),
                            ("public", "Public"),
                            ("business", "Business"),
                            ("personal", "Personal"),
                        ],
                        default="personal",
                        max_length=255,
                    ),
                ),
                ("pending", models.BooleanField(default=False)),
                ("proccess", models.BooleanField(default=False)),
                ("completed", models.BooleanField(default=False)),
                ("from_date", models.DateField(blank=True, null=True)),
                ("to_date", models.DateField(blank=True, null=True)),
                ("size", models.IntegerField()),
                ("time", models.CharField(max_length=200)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("commercial", "Commercial"),
                            ("public", "Public"),
                            ("business", "Business"),
                            ("personal", "Personal"),
                        ],
                        default="personal",
                        max_length=255,
                    ),
                ),
                ("total_price", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StorageFacilityOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feedback", models.BooleanField(default=False)),
                ("pending", models.BooleanField(default=False)),
                ("completed", models.BooleanField(default=False)),
                ("months", models.IntegerField(default=1)),
                ("starting_date", models.DateField()),
                ("ending_date", models.DateField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order",
                        to="order.userorder",
                    ),
                ),
            ],
        ),
    ]
