# Generated by Django 4.2 on 2023-09-18 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("storage_units", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("service_providers", "0001_initial"),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storagefacilityorder",
            name="unit_order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unit_order",
                to="storage_units.storageunit",
            ),
        ),
        migrations.AddField(
            model_name="oraganizerorder",
            name="from_location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="service_providers.location",
            ),
        ),
        migrations.AddField(
            model_name="oraganizerorder",
            name="organizer_order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="service_providers.organizers",
            ),
        ),
        migrations.AddField(
            model_name="oraganizerorder",
            name="to_location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_location",
                to="service_providers.location",
            ),
        ),
        migrations.AddField(
            model_name="oraganizerorder",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="moverorder",
            name="from_location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="service_providers.location",
            ),
        ),
        migrations.AddField(
            model_name="moverorder",
            name="mover_order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="service_providers.movers",
            ),
        ),
        migrations.AddField(
            model_name="moverorder",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="storage_unit",
            field=models.ManyToManyField(blank=True, to="storage_units.storageunit"),
        ),
        migrations.AddField(
            model_name="cart",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
